# Generated by Django 4.2.5 on 2023-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address_one',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='address_two',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='province',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='middle_name',
            field=models.CharField(default='Moscoso', max_length=150),
            preserve_default=False,
        ),
    ]
