# Generated by Django 4.2.5 on 2023-10-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_address_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
