# Generated by Django 4.2.5 on 2023-10-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_addressinformation_residentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='address_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.addressinformation'),
            preserve_default=False,
        ),
    ]
