# Generated by Django 4.2.5 on 2023-10-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_delete_residentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('resident', 'Resident'), ('healthworker', 'Health Worker'), ('admin', 'Admin')], default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
