# Generated by Django 4.2.5 on 2023-11-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_user_type_useraccount_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressInformation',
            new_name='AddressDetails',
        ),
    ]
