# Generated by Django 4.2.5 on 2023-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_addressinformation_addressdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('healthworker', 'Health Worker'), ('admin', 'Admin')], max_length=100),
        ),
    ]
