# Generated by Django 4.2.5 on 2023-11-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_useraccount_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_type',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_role',
            field=models.CharField(choices=[('resident', 'Resident'), ('healthworker', 'Health Worker'), ('admin', 'Admin')], default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
