# Generated by Django 4.2.5 on 2023-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccount_user_type_useraccount_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_info',
            new_name='address_details',
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_line_three',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='barangay',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='province',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
