# Generated by Django 4.2.5 on 2023-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('r', 'Rather not say')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
