package com.crawler.backend.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Permissions {
    USER_READ("USER:READ"),
    USER_CREATE("USER:CREATE"),
    USER_UPDATE("USER:UPDATE"),
    USER_DELETE("USER:DELETE"),
    PROFILE_CREATE("PROFILE:CREATE"),
    PROFILE_READ("PROFILE:READ"),
    PROFILE_UPDATE("PROFILE:UPDATE"),
    PROFILE_DELETE("PROFILE:DELETE"),
    RECORD_CREATE("RECORD:CREATE"),
    RECORD_READ("RECORD:READ"),
    RECORD_UPDATE("RECORD:UPDATE"),
    RECORD_DELETE("RECORD:DELETE"),
    RECORD_COUNT_READ("RECORD_COUNT:READ"),
    DEPARTMENT_USAGE_READ("DEPARTMENT_USAGE:READ"),
    HEALTH_METRICS_READ("HEALTH_METRICS:READ"),
    DEMOGRAPHICS_ANALYSIS_READ("DEMOGRAPHICS_ANALYSIS:READ");

    private final String name;
}
