events {}

http {
    server {
        listen 80;
        server_name user.localhost admin.localhost api.localhost;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name user.localhost;

        ssl_certificate /etc/nginx/certs/health-watch.pem;
        ssl_certificate_key /etc/nginx/certs/health-watch-key.pem;

        location / {
            proxy_pass http://user_ui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen 443 ssl;
        server_name admin.localhost;

        ssl_certificate /etc/nginx/certs/health-watch.pem;
        ssl_certificate_key /etc/nginx/certs/health-watch-key.pem;

        location / {
            proxy_pass http://admin_ui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen 443 ssl;
        server_name api.localhost;

        ssl_certificate /etc/nginx/certs/health-watch.pem;
        ssl_certificate_key /etc/nginx/certs/health-watch-key.pem;

        location / {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}