server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

# JWT
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-duration-minute: 5
  access-token-duration-second: 300
  refresh-token-duration-day: 7
  refresh-token-duration-second: 604800

  access-cookie-name: access_token
  refresh-cookie-name: refresh_token

# RABBITMQ
rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  default_user: ${RABBITMQ_DEFAULT_USER}
  default_password: ${RABBITMQ_DEFAULT_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
