spring:
  application:
    name: backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
        dialect:
          "[storage_engine]": innodb
    hibernate:
      ddl-auto: update

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port} 
      username: ${spring.data.redis.username}
      password: ${spring.data.redis.password}
  cache:
    type: ${spring.cache.type}

  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.default_user}
    password: ${rabbitmq.default_password}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: INFO
    org:
      springdoc: INFO
      springframework:
        web: INFO
        data:
          jpa:
            repository: ERROR
          redis: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
    com:
      crawler:
        backend: INFO

springdoc:
  override-with-generic-response: false

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,metrics
#   endpoint:
#     health:
#       show-details: always
