spring.application.name=backend

# Server port
server.port=8080

# Datasource connection
spring.sql.init.platform=mysql
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show-sql=true

# Logging
logging.level.org.springframework=ERROR
logging.level.com.numericaideas=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER