server:
  port: ${SERVER_PORT}
  ssl:
    enabled: true
    key-store: "classpath:keystore.p12"
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

# JWT
jwt:
  access-token-duration-minute: 5
  access-token-duration-second: 300
  refresh-token-duration-day: 7
  refresh-token-duration-second: 604800

  access-cookie-name: access_token
  refresh-cookie-name: refresh_token

# RABBITMQ
rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  default_user: ${RABBITMQ_USER}
  default_password: ${RABBITMQ_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true