spring.application.name=backend

# Server
spring.profiles.active=dev

# Datasource connection
spring.sql.init.platform=mysql
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true

# Logging
# logging.level.org.springframework=ERROR
# logging.level.com.numericaideas=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type=TRACE
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.level.web=DEBUG

#
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

#
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/swagger.html
springdoc.paths-to-match=/api/v1/**

#
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Spring Security
# spring.security.user.name=sys_dev
# spring.security.user.password=pwd123