name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew clean test

  admin-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  user-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-user

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend-user/package-lock.json

      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
